stages:
  - build
  - test

build:
  stage: build
  image: maven:3.8.5-openjdk-17
  script:
    - mvn -settings settings.xml clean package -Dskiptests
  artifacts:
    paths:
      - target/*.jar

unit-test:
  stage: test
  image: maven:3.8.5-openjdk-17
  needs:
    - build
  allow_failure: true
  script:
    - mvn -settings settings.xml test

sonarqube:
  stage: test
  image: maven:3.8.5-openjdk-17
  needs:
    - build
  allow_failure: true
  variables:
    SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
    GIT_DEPTH: 0
  script:
    - mvn -settings settings.xml test
    - mvn sonar:sonar -settings settings.xml
      -Dsonar.coverage.exclusions=**/MainApplication.java
      -Dsonar.qualitygate.wait=true
      -Dsonar.projectKey=${CI_PROJECT_NAME}-${CI_COMMIT_BRANCH}
  cache:
    key: $CI_JOB_NAME
    paths:
      - .sonar/cache