stages:
  - image
  - deploy

kaniko:
  stage: image
  image: kaniko/executor:debug
  before_script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"REGISTRY_URL\":{\"auth\":\"$(printf "%s:%s" "${USER}" "${PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
  script:
    - export IFS=''
    - >-
      /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --insecure
      --insecure-pull
      --destination "${REGISTRY_URL}/${PATH}/${PROJECT}:${TAG}"
      --insecure-registry $REGISTRY_URL
      --skip-tls-verify
      --skip-tls-verify-pull
      --skip-tls-verify-registry $REGISTRY_URL

deploy:
  stage: deploy
  environment: Production
  image: deployer:latest
  needs:
    - kaniko
  before_script:
    - helm repo add any-name
    - helm upgrade $CI_PROJECT_NAME any-name/package-name --install --values helm-values.yaml --wait --atomic